### ISSUE TITLE
Yuan Completed the Get Data Assignment

### ISSUE THREAD

**Issue by yfang6** [yfang6/Archaeobotanical_Project#1]
Hi Aaron,

I have completed the Get Data Assignment. Thanks!
@AaronGullickson

Sincerely,
Yuan

**Comment by AaronGullickson** [comment]
@yfang6 This looks good. I do note however that when you read in the data via CSV, you are getting some weird results that I think come from the Excel document.

If the original document was an excel document as it appears, then I think you are better off just reading directly from Excel using the `readxl` library. There are two reasons for this. 

1. If you have to save the data as CSV to read into R, then you might get into a problem if the excel data are ever updated. If you forget to re-save as CSV, then you will end up with two inconsistent documents in your input directory. 
2. The `readxl` library seems to handle the excel formatting in the original document better than the CSV. For example in the CSV you are getting "#DIV/0!" responses and "%" being applied to numbers. When I tried it out with `readxl`, it read in much more cleanly.

I didn't change the code, but you can replace your read.csv input with: 

```r
library(readxl)
huizui <- read_excel("analysis/input/Huizui.xlsx")
```

You will need to make sure that `readxl` is installed with `insall.packages("readxl")`.
