### ISSUE TITLE
Yuan Completed the Lab Notebook Assignment and Several Questions about the Final Report

### ISSUE THREAD

**Issue by yfang6** [yfang6/Archaeobotanical_Project#3]
Hi Aaron,

Sorry that I forgot to create an issue for the Lab Notebook Assignment. I finished it but I might still modify its codes. 

I still have questions about what was discussed during your office hours on Tuesday:

1. I'm still not sure about the interpretations of interaction terms. After adding the coefficient of Ditch to that of Yangshao:Ditch then exp the sum, should I interpret the result as "Among ditch samples, the total seed density from the Yangshao period is 28% more than that from the Erlitou period"?

2. The tables for models do not show AIC and BIC. How could I add these results to the table?

Thanks!
@AaronGullickson

Sincerely,
Yuan

**Comment by AaronGullickson** [comment]
@yfang6 

1. The interpretation is correct but not the math. If you want that interpretation you need to add the Yangshao main effect with the Yangshao:Ditch interaction, then it would be correct. . The way you are doing it says "Within the Yangshao period, ditch samples had 28% higher seed density than ash pit samples." 

2. Yes, I think you lose the BIC with the quaispoisson approach. You might be able to reconstruct it manually from the deviance, but you probably don't need to worry about this at such a late stage.
